services:
  - type: web
    name: ats-backend
    env: python
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y tesseract-ocr poppler-utils
      pip install -r requirements.txt
    startCommand: uvicorn ats_backend.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
